# Generated by Django 5.1.3 on 2025-06-09 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='apartment',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Ngày đăng')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Quản lý thông báo',
            },
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('charge_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã khoản thu')),
                ('name', models.CharField(max_length=255, verbose_name='Tên khoản thu')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('deadline', models.DateField(verbose_name='Hạn thanh toán')),
                ('category', models.CharField(choices=[('Tiền điện', 'Tiền điện'), ('Tiền nước', 'Tiền nước'), ('Phí dịch vụ', 'Phí dịch vụ'), ('Phí quản lý', 'Phí quản lý'), ('Phí gửi xe', 'Phí gửi xe'), ('Khác', 'Khác')], default='Khác', max_length=50, verbose_name='Loại khoản thu')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('target_room', models.ManyToManyField(related_name='charges', to='bluemoonapp.apartment', verbose_name='Đối tượng thu')),
            ],
            options={
                'verbose_name': 'Khoản thu',
                'verbose_name_plural': 'Quản lý khoản thu',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Họ')),
                ('last_name', models.CharField(max_length=50, verbose_name='Tên')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('cccd', models.CharField(default='106872712222', max_length=12, unique=True, verbose_name='Số CCCD')),
                ('email', models.EmailField(default='lol@gmail.com', max_length=254)),
                ('phone_number', models.CharField(default='0123456789', max_length=10, verbose_name='Số điện thoại')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='bluemoonapp.apartment', verbose_name='Số phòng')),
            ],
            options={
                'verbose_name': 'Nhân khẩu',
                'verbose_name_plural': 'Quản lý nhân khẩu',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bluemoonapp.apartment', verbose_name='Số phòng')),
            ],
            options={
                'verbose_name': 'Quản lý thông báo các hộ',
                'verbose_name_plural': 'Quản lý thông báo các hộ',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã thanh toán')),
                ('amount', models.PositiveIntegerField(verbose_name='Số tiền')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('status', models.BooleanField(default=False, verbose_name='Trạng thái')),
                ('charge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bluemoonapp.charge', verbose_name='Mã khoản thu')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bluemoonapp.apartment', verbose_name='Số phòng')),
            ],
            options={
                'verbose_name': 'Khoản thanh toán',
                'verbose_name_plural': 'Quản lý khoản thanh toán',
            },
        ),
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Tên tài khoản')),
                ('registry_email', models.EmailField(default='example@gmail.com', max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=10, unique=True, verbose_name='Số điện thoại')),
                ('is_approved', models.BooleanField(choices=[(False, 'Chưa duyệt'), (True, 'Đã duyệt')], default=False, max_length=10, verbose_name='Trạng thái duyệt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tài khoản hoạt động')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='bluemoonapp.apartment', verbose_name='Số phòng')),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Quản lý tài khoản',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=30, verbose_name='Biển số xe')),
                ('type_vehicle', models.IntegerField(choices=[(1, 'Xe đạp'), (2, 'Xe máy'), (3, 'Ô tô')], verbose_name='Loại xe')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='bluemoonapp.apartment', verbose_name='Số phòng')),
            ],
            options={
                'verbose_name': 'Thông tin gửi xe',
                'verbose_name_plural': 'Quản lý gửi xe',
            },
        ),
    ]
